"""
Helper utilities for setting up, managing, and restoring OpenAI Codex CLI configuration.
Supports safe backups, zero-config setup, ephemeral test execution, and full model catalog integration.
"""

import json
import os
import re
import shutil
from typing import Any


def get_codex_dir(custom_dir: str | None = None) -> str:
    """Returns the base directory for Codex configuration (~/.codex or CODEX_HOME)."""
    if custom_dir:
        return os.path.abspath(custom_dir)
    return os.path.abspath(os.environ.get("CODEX_HOME") or os.path.expanduser("~/.codex"))


def get_catalog_dict() -> dict[str, Any]:
    """Loads the official Antigravity Codex models catalog."""
    possible_paths = [
        os.path.join(os.path.dirname(os.path.abspath(__file__)), "codex_models.json"),
        os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "codex_models.json"),
    ]
    for p in possible_paths:
        if os.path.isfile(p):
            with open(p, encoding="utf-8") as f:
                return json.load(f)

    # Fallback minimal catalog
    return {
        "models": [
            {
                "slug": "gemini-3.8-flash-high",
                "display_name": "Gemini 3.8 Flash (High Reasoning)",
                "description": "Google Flagship model with deep thinking & reasoning capabilities (Default)",
                "visibility": "list",
                "shell_type": "unified_exec",
                "apply_patch_tool_type": "freeform",
                "supported_reasoning_levels": [{"effort": "high", "description": "High reasoning depth"}],
            }
        ]
    }


def update_toml_content(original_content: str, updates: dict[str, str]) -> str:
    """
    Updates or inserts top-level key/value string pairs in TOML content without breaking comments or formatting.
    """
    content = original_content
    for key, value in updates.items():
        pattern = re.compile(rf'^{re.escape(key)}\s*=\s*.*$', re.MULTILINE)
        new_line = f'{key} = "{value}"'
        if pattern.search(content):
            content = pattern.sub(new_line, content)
        else:
            if content and not content.endswith("\n"):
                content += "\n"
            content += f"{new_line}\n"
    return content


def setup_codex(
    codex_dir: str | None = None,
    port: int = 8000,
    model: str = "gemini-3.8-flash-high",
) -> dict[str, Any]:
    """
    Configures Codex CLI to use Antigravity Proxy with the full 25+ model catalog.
    Safely creates a backup of any existing configuration before making changes.
    """
    base_dir = get_codex_dir(codex_dir)
    os.makedirs(base_dir, exist_ok=True)

    catalog_path = os.path.join(base_dir, "antigravity_models.json")
    config_path = os.path.join(base_dir, "config.toml")
    backup_path = os.path.join(base_dir, "config.toml.agy_backup")

    # 1. Save full model catalog
    catalog_data = get_catalog_dict()
    with open(catalog_path, "w", encoding="utf-8") as f:
        json.dump(catalog_data, f, indent=2)
    try:
        os.chmod(catalog_path, 0o600)
    except Exception:
        pass

    # 2. Handle backup
    backup_created = False
    if os.path.isfile(config_path):
        if not os.path.isfile(backup_path):
            shutil.copy2(config_path, backup_path)
            backup_created = True
            try:
                os.chmod(backup_path, 0o600)
            except Exception:
                pass
        with open(config_path, encoding="utf-8") as f:
            content = f.read()
    else:
        content = (
            "# Codex CLI configuration generated by Antigravity Proxy\n"
            "# Run 'agy-proxy restore-codex' to restore original settings\n"
        )

    # 3. Apply updates
    proxy_url = f"http://127.0.0.1:{port}/v1"
    updates = {
        "openai_base_url": proxy_url,
        "model": model,
        "model_catalog_json": catalog_path,
    }
    new_content = update_toml_content(content, updates)

    with open(config_path, "w", encoding="utf-8") as f:
        f.write(new_content)
    try:
        os.chmod(config_path, 0o600)
    except Exception:
        pass

    return {
        "status": "ok",
        "message": "Codex CLI successfully configured for Antigravity Proxy.",
        "backup_created": backup_created,
        "backup_path": backup_path if (backup_created or os.path.isfile(backup_path)) else None,
        "config_path": config_path,
        "catalog_path": catalog_path,
        "models_count": len(catalog_data.get("models", [])),
        "proxy_url": proxy_url,
        "model": model,
    }


def restore_codex(codex_dir: str | None = None) -> dict[str, Any]:
    """
    Restores the original Codex CLI configuration from backup and cleans up proxy additions.
    """
    base_dir = get_codex_dir(codex_dir)
    config_path = os.path.join(base_dir, "config.toml")
    backup_path = os.path.join(base_dir, "config.toml.agy_backup")
    catalog_path = os.path.join(base_dir, "antigravity_models.json")

    restored_from_backup = False
    cleaned_config = False

    if os.path.isfile(backup_path):
        shutil.copy2(backup_path, config_path)
        try:
            os.remove(backup_path)
        except OSError:
            pass
        restored_from_backup = True
    elif os.path.isfile(config_path):
        with open(config_path, encoding="utf-8") as f:
            content = f.read()
        
        # Remove proxy-specific lines
        lines = content.splitlines()
        filtered = [
            l for l in lines
            if not any(
                k in l for k in [
                    "antigravity_models.json",
                    "Codex CLI configuration generated by Antigravity Proxy",
                    "Run 'agy-proxy restore-codex'",
                ]
            ) and not (l.startswith("openai_base_url") and "127.0.0.1" in l)
        ]
        
        # If file was completely generated by us or is now empty comments, remove it
        meaningful_lines = [l.strip() for l in filtered if l.strip() and not l.strip().startswith("#")]
        if not meaningful_lines:
            try:
                os.remove(config_path)
                cleaned_config = True
            except OSError:
                pass
        else:
            with open(config_path, "w", encoding="utf-8") as f:
                f.write("\n".join(filtered) + "\n")
            cleaned_config = True

    # Optionally remove antigravity_models.json
    if os.path.isfile(catalog_path):
        try:
            os.remove(catalog_path)
        except OSError:
            pass

    return {
        "status": "ok",
        "message": (
            "Successfully restored original ~/.codex/config.toml from backup."
            if restored_from_backup else
            "Removed Antigravity Proxy settings from ~/.codex/config.toml."
            if cleaned_config else
            "No active Antigravity Proxy configuration found in ~/.codex/."
        ),
        "restored_from_backup": restored_from_backup,
        "cleaned_config": cleaned_config,
    }


def get_codex_status(codex_dir: str | None = None, port: int = 8000) -> dict[str, Any]:
    """
    Checks if Codex CLI is installed and whether it is currently configured for Antigravity Proxy.
    """
    base_dir = get_codex_dir(codex_dir)
    config_path = os.path.join(base_dir, "config.toml")
    backup_path = os.path.join(base_dir, "config.toml.agy_backup")
    catalog_path = os.path.join(base_dir, "antigravity_models.json")

    # Check executable
    codex_bin = shutil.which("codex")
    if not codex_bin:
        default_local_bin = os.path.expanduser("~/.local/bin/codex")
        if os.path.isfile(default_local_bin) and os.access(default_local_bin, os.X_OK):
            codex_bin = default_local_bin

    is_configured = False
    active_model = None
    configured_url = None

    if os.path.isfile(config_path):
        try:
            with open(config_path, encoding="utf-8") as f:
                content = f.read()
            
            url_match = re.search(r'openai_base_url\s*=\s*["\']([^"\']+)["\']', content)
            model_match = re.search(r'model\s*=\s*["\']([^"\']+)["\']', content)
            catalog_match = re.search(r'model_catalog_json\s*=\s*["\']([^"\']+)["\']', content)

            if url_match:
                configured_url = url_match.group(1)
            if model_match:
                active_model = model_match.group(1)

            expected_port = str(port)
            if configured_url and (f":{expected_port}" in configured_url or "localhost" in configured_url or "127.0.0.1" in configured_url):
                is_configured = True
        except Exception:
            pass

    return {
        "installed": bool(codex_bin),
        "executable": codex_bin,
        "is_configured": is_configured,
        "config_exists": os.path.isfile(config_path),
        "backup_exists": os.path.isfile(backup_path),
        "catalog_exists": os.path.isfile(catalog_path),
        "active_model": active_model,
        "configured_url": configured_url,
        "config_path": config_path,
        "backup_path": backup_path,
    }
